---
anima4_bot:
  rsshub_feed_scraper:
    enabled_sources:
      - pixiv
      # - twitter # Twitter requires authentication due to API limitations from their side
  database:
    filename: data/rss_feeds.db
    feeds_table_name: rss_feeds
  telegram:
    bot_token: token_id:auth_token
    channel_id: 1234567890
    admins_list:
      - 1111111
      - 2222222
