---
anima4_bot:
  rsshub_feed_scraper:
    enabled_sources:
      - pixiv
      # - twitter # Twitter requires authentication due to API limitations from their side
    check_after_date: 2023-01-01T00:00:00Z # ISO 8601 format with timezone
  database:
    filename: data/rss_feeds.db
    feeds_table_name: rss_feeds
  telegram:
    bot_token: token_id:auth_token
    channel_id: 1234567890
    admins_list:
      - 1111111
      - 2222222
